<a href="https://colab.research.google.com/github/arya2910/online-assessment-plagiarism-checker/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://s3.amazonaws.com/video.udacity-data.com/topher/2019/January/5c4147f9_data/data.zip
!unzip data

--2022-02-06 13:28:15--  https://s3.amazonaws.com/video.udacity-data.com/topher/2019/January/5c4147f9_data/data.zip
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.192.40
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.192.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 113826 (111K) [application/zip]
Saving to: ‘data.zip.2’

data.zip.2          100%[===================>] 111.16K  --.-KB/s    in 0.06s

2022-02-06 13:28:16 (1.83 MB/s) - ‘data.zip.2’ saved [113826/113826]

Archive:  data.zip
replace data/.DS_Store? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
csv_file = 'data/file_information.csv'
plagiarism_df = pd.read_csv(csv_file)

plagiarism_df.head()

             File Task Category
0  g0pA_taska.txt    a      non
1  g0pA_taskb.txt    b      cut
2  g0pA_taskc.txt    c    light
3  g0pA_taskd.txt    d    heavy
4  g0pA_taske.txt    e      non

In [ ]:
# Read in a csv file and return a transformed dataframe
def numerical_dataframe(csv_file='data/file_information.csv'):
    
    
    # read in csv
    df = pd.read_csv(csv_file)
    
    # replace string category with numerical category
    numerical_categories = {'non': 0, 'heavy': 1, 'light': 2, 'cut': 3, 'orig': -1}
    
    for key, val in numerical_categories.items():
        df = df.replace(key, val)
        
        
    # add class labels 
    df['Class'] = np.where(df['Category'] != 0, 1, 0) # label whether plagiarized (1) or not (0)
    df['Class'] = np.where(df['Category'] == -1, -1, df['Class']) # -1 category is origin => class is -1 (meaningless)
    
    return df

In [ ]:
# informal testing, print out the results of a called function
# create new `transformed_df`
transformed_df = numerical_dataframe(csv_file ='data/file_information.csv')

# check work
# check that all categories of plagiarism have a class label = 1
transformed_df.head(10)

             File Task  Category  Class
0  g0pA_taska.txt    a         0      0
1  g0pA_taskb.txt    b         3      1
2  g0pA_taskc.txt    c         2      1
3  g0pA_taskd.txt    d         1      1
4  g0pA_taske.txt    e         0      0
5  g0pB_taska.txt    a         0      0
6  g0pB_taskb.txt    b         0      0
7  g0pB_taskc.txt    c         3      1
8  g0pB_taskd.txt    d         2      1
9  g0pB_taske.txt    e         1      1

In [ ]:
# test cell that creates `transformed_df`, if tests are passed

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""

# importing tests
import problem_unittests as tests

# test numerical_dataframe function
tests.test_numerical_df(numerical_dataframe)

# if above test is passed, create NEW `transformed_df`
transformed_df = numerical_dataframe(csv_file ='data/file_information.csv')

# check work
print('\nExample data: ')
transformed_df.head()

Tests Passed!

Example data:

             File Task  Category  Class
0  g0pA_taska.txt    a         0      0
1  g0pA_taskb.txt    b         3      1
2  g0pA_taskc.txt    c         2      1
3  g0pA_taskd.txt    d         1      1
4  g0pA_taske.txt    e         0      0

In [ ]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
import helpers 

# create a text column 
text_df = helpers.create_text_column(transformed_df)
text_df.head()

             File  ...                                               Text
0  g0pA_taska.txt  ...  inheritance is a basic concept of object orien...
1  g0pA_taskb.txt  ...  pagerank is a link analysis algorithm used by ...
2  g0pA_taskc.txt  ...  the vector space model also called term vector...
3  g0pA_taskd.txt  ...  bayes theorem was names after rev thomas bayes...
4  g0pA_taske.txt  ...  dynamic programming is an algorithm design tec...

[5 rows x 5 columns]

In [ ]:
# after running the cell above
# check out the processed text for a single file, by row index
row_idx = 9 # feel free to change this index

sample_text = text_df.iloc[0]['Text']

print('Sample processed text:\n\n', sample_text)

Sample processed text:

 inheritance is a basic concept of object oriented programming where the basic idea is to create new classes that add extra detail to existing classes this is done by allowing the new classes to reuse the methods and variables of the existing classes and new methods and classes are added to specialise the new class inheritance models the is kind of relationship between entities or objects  for example postgraduates and undergraduates are both kinds of student this kind of relationship can be visualised as a tree structure where student would be the more general root node and both postgraduate and undergraduate would be more specialised extensions of the student node or the child nodes  in this relationship student would be known as the superclass or parent class whereas  postgraduate would be known as the subclass or child class because the postgraduate class extends the student class  inheritance can occur on several layers where if visualised would display a larger tree structure for example we could further extend the postgraduate node by adding two extra extended classes to it called  msc student and phd student as both these types of student are kinds of postgraduate student this would mean that both the msc student and phd student classes would inherit methods and variables from both the postgraduate and student classes

In [ ]:
random_seed = 1 # can change; set for reproducibility

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
import helpers

# create new df with Datatype (train, test, orig) column
# pass in `text_df` from above to create a complete dataframe, with all the information you need
complete_df = helpers.train_test_dataframe(text_df, random_seed=random_seed)

# check results
complete_df[90:100]

              File  ... Datatype
90  g4pE_taska.txt  ...    train
91  g4pE_taskb.txt  ...    train
92  g4pE_taskc.txt  ...    train
93  g4pE_taskd.txt  ...    train
94  g4pE_taske.txt  ...     test
95  orig_taska.txt  ...     orig
96  orig_taskb.txt  ...     orig
97  orig_taskc.txt  ...     orig
98  orig_taskd.txt  ...     orig
99  orig_taske.txt  ...     orig

[10 rows x 6 columns]

In [ ]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer

# helper functions
def get_answer_and_source_text(df, answer_filename):
    """
    Finds the correct row in dataframe based on filename and returns the text. Does this for
    both the answer text and the source text.
    
    Args:
        df (pd.Dataframe): stores the answers and sources
        answer_filename (string): filename for the answer, to be used to find the text
        
    Returns: 
        answer_text, source_text
    """
    # print('Getting answer and source texts...\n')
    
    # find the answer text and its task
    answer_row = df[df['File'] == answer_filename]
    answer_text = answer_row.iloc[0]['Text']
    task = answer_row.iloc[0]['Task']

    # used to help find corresponding source text
    task_bool = df['Task'] == task
    category_bool = df['Category'] == -1
    
    # find the source text
    source_row = df[task_bool & category_bool]
    source_text = source_row.iloc[0]['Text']
    
    return answer_text, source_text

In [ ]:
def get_vocab_and_counts(answer_text, source_text, n):
    """
    Using CountVectorizer, create a vocabulary based on the answer and source text. 
    Then, count the number of occurences of each ngram in the vocabulary for answer
    and source text.
    
    Args:
        answer_text (string): answer text
        source_test (string): source text to be compared with answer text
        n: the n in n-gram
    
    Returns:
        vocab (dict): generated by fitting the CountVectorizer to answer and source text
        counts.toarray() (2D numpy array): the ngram counts for answer and source text
    """
    counts_ngram = CountVectorizer(analyzer='word', ngram_range=(n,n))
    vocab = counts_ngram.fit([answer_text, source_text]).vocabulary_
    counts = counts_ngram.fit_transform([answer_text, source_text])
    
    return vocab, counts.toarray()

In [ ]:
# Calculate the ngram containment for one answer file/source file pair in a df
def calculate_containment(df, n, answer_filename):
    '''Calculates the containment between a given answer text and its associated source text.
       This function creates a count of ngrams (of a size, n) for each text file in our data.
       Then calculates the containment by finding the ngram count for a given answer text, 
       and its associated source text, and calculating the normalized intersection of those counts.
       :param df: A dataframe with columns,
           'File', 'Task', 'Category', 'Class', 'Text', and 'Datatype'
       :param n: An integer that defines the ngram size
       :param answer_filename: A filename for an answer text in the df, ex. 'g0pB_taskd.txt'
       :return: A single containment value that represents the similarity
           between an answer text and its source text.
    '''
        
    # get answer and source text
    answer_text, source_text = get_answer_and_source_text(df, answer_filename)
    # print(answer_text, '\n\n', source_text) # test
    
    
    # print('Comparing answer and source texts. Calculating containment...\n')
    
    # create vocabulary and then count the occurences of each ngram
    vocab, ngram_counts = get_vocab_and_counts(answer_text, source_text, n)
    # print(dict(list(vocab.items())[0:10]), '\n\n', ngram_counts) #test
    
    # calculate containment 
    
    # FULL DISCLOSURE NOTE: the idea to use np.min came from DavidH's suggestion in the Student Hub
    intersection_list = np.amin(ngram_counts, axis = 0) # intersection of counts, taking min column-wise
    # print(intersection_list[0:10]) #test

    intersection = np.sum(intersection_list) # summing the intersection count
    count_ngram_A = np.sum(ngram_counts[0]) # normalizer

    return intersection / count_ngram_A

In [ ]:
# select a value for n
n = 3

# indices for first few files
test_indices = range(5)

# iterate through files and calculate containment
category_vals = []
containment_vals = []
for i in test_indices:
    # get level of plagiarism for a given file index
    category_vals.append(complete_df.loc[i, 'Category'])
    # calculate containment for given file and n
    filename = complete_df.loc[i, 'File']
    c = calculate_containment(complete_df, n, filename)
    containment_vals.append(c)

# print out result, does it make sense?
print('Original category values: \n', category_vals)
print()
print(str(n)+'-gram containment values: \n', containment_vals)

Original category values:
 [0, 3, 2, 1, 0]

3-gram containment values:
 [0.009345794392523364, 0.9641025641025641, 0.6136363636363636, 0.15675675675675677, 0.031746031746031744]

In [ ]:
# run this test cell
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test containment calculation
# params: complete_df from before, and containment function
tests.test_containment(complete_df, calculate_containment)

Tests Passed!

In [ ]:
# Compute the normalized LCS given an answer text and a source text
def lcs_norm_word(answer_text, source_text):
    '''Computes the longest common subsequence of words in two texts; returns a normalized value.
       :param answer_text: The pre-processed text for an answer text
       :param source_text: The pre-processed text for an answer's associated source text
       :return: A normalized LCS value'''
    
    # separate into list entries to simulate matrix
    answer_words = answer_text.split()
    source_words = source_text.split()
    
    n = len(answer_words)
    m = len(source_words)
    
    
    lcs_matrix = np.zeros((n+1, m+1))
    
    # iterate thru words, finding longest common subsequence using dynamic programming
    i = j = 1
    for answer_word in answer_words:
        j = 1
        for source_word in source_words:
            if answer_word == source_word:
                lcs_matrix[i][j] = lcs_matrix[i-1][j-1] + 1
            else:
                lcs_matrix[i][j] = max(lcs_matrix[i][j-1], lcs_matrix[i-1][j]) 
            
            j += 1
        
        i += 1
        
        
    lcs_normalized = lcs_matrix[n][m] / n
    
    return lcs_normalized

In [ ]:
# Run the test scenario from above
# does your function return the expected value?

A = "i think pagerank is a link analysis algorithm used by google that uses a system of weights attached to each element of a hyperlinked set of documents"
S = "pagerank is a link analysis algorithm used by the google internet search engine that assigns a numerical weighting to each element of a hyperlinked set of documents"

# calculate LCS
lcs = lcs_norm_word(A, S)
print('LCS = ', lcs)


# expected value test
assert lcs==20/27., "Incorrect LCS value, expected about 0.7408, got "+str(lcs)

print('Test passed!')

LCS =  0.7407407407407407
Test passed!

In [ ]:
# run test cell
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test lcs implementation
# params: complete_df from before, and lcs_norm_word function
tests.test_lcs(complete_df, lcs_norm_word)

Tests Passed!

In [ ]:
# test on your own
test_indices = range(5) # look at first few files

category_vals = []
lcs_norm_vals = []
# iterate through first few docs and calculate LCS
for i in test_indices:
    category_vals.append(complete_df.loc[i, 'Category'])
    # get texts to compare
    answer_text = complete_df.loc[i, 'Text'] 
    task = complete_df.loc[i, 'Task']
    # we know that source texts have Class = -1
    orig_rows = complete_df[(complete_df['Class'] == -1)]
    orig_row = orig_rows[(orig_rows['Task'] == task)]
    source_text = orig_row['Text'].values[0]
    
    # calculate lcs
    lcs_val = lcs_norm_word(answer_text, source_text)
    lcs_norm_vals.append(lcs_val)

# print out result, does it make sense?
print('Original category values: \n', category_vals)
print()
print('Normalized LCS values: \n', lcs_norm_vals)

Original category values:
 [0, 3, 2, 1, 0]

Normalized LCS values:
 [0.1917808219178082, 0.8207547169811321, 0.8464912280701754, 0.3160621761658031, 0.24257425742574257]

In [ ]:
def create_containment_features(df, n, column_name=None):
    
    containment_values = []
    
    if(column_name==None):
        column_name = 'c_'+str(n) # c_1, c_2, .. c_n
    
    # iterates through dataframe rows
    for i in df.index:
        file = df.loc[i, 'File']
        # Computes features using calculate_containment function
        if df.loc[i,'Category'] > -1:
            c = calculate_containment(df, n, file)
            containment_values.append(c)
        # Sets value to -1 for original tasks 
        else:
            containment_values.append(-1)
    
    print(str(n)+'-gram containment features created!')
    return containment_values

In [ ]:
def create_lcs_features(df, column_name='lcs_word'):
    
    lcs_values = []
    
    # iterate through files in dataframe
    for i in df.index:
        # Computes LCS_norm words feature using function above for answer tasks
        if df.loc[i,'Category'] > -1:
            # get texts to compare
            answer_text = df.loc[i, 'Text'] 
            task = df.loc[i, 'Task']
            # we know that source texts have Class = -1
            orig_rows = df[(df['Class'] == -1)]
            orig_row = orig_rows[(orig_rows['Task'] == task)]
            source_text = orig_row['Text'].values[0]

            # calculate lcs
            lcs = lcs_norm_word(answer_text, source_text)
            lcs_values.append(lcs)
        # Sets to -1 for original tasks 
        else:
            lcs_values.append(-1)

    print('LCS features created!')
    return lcs_values

In [ ]:
ngram_range = range(1,8)


# The following code may take a minute to run, depending on your ngram_range
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
features_list = []

# Create features in a features_df
all_features = np.zeros((len(ngram_range)+1, len(complete_df)))

# Calculate features for containment for ngrams in range
i=0
for n in ngram_range:
    column_name = 'c_'+str(n)
    features_list.append(column_name)
    # create containment features
    all_features[i]=np.squeeze(create_containment_features(complete_df, n))
    i+=1

# Calculate features for LCS_Norm Words 
features_list.append('lcs_word')
all_features[i]= np.squeeze(create_lcs_features(complete_df))

# create a features dataframe
features_df = pd.DataFrame(np.transpose(all_features), columns=features_list)

# Print all features/columns
print()
print('Features: ', features_list)
print()

1-gram containment features created!
2-gram containment features created!
3-gram containment features created!
4-gram containment features created!
5-gram containment features created!
6-gram containment features created!
7-gram containment features created!
LCS features created!

Features:  ['c_1', 'c_2', 'c_3', 'c_4', 'c_5', 'c_6', 'c_7', 'lcs_word']

In [ ]:
features_df.head(10)

        c_1       c_2       c_3  ...       c_6       c_7  lcs_word
0  0.398148  0.079070  0.009346  ...  0.000000  0.000000  0.191781
1  1.000000  0.984694  0.964103  ...  0.901042  0.879581  0.820755
2  0.869369  0.719457  0.613636  ...  0.382488  0.319444  0.846491
3  0.593583  0.268817  0.156757  ...  0.060440  0.044199  0.316062
4  0.544503  0.115789  0.031746  ...  0.000000  0.000000  0.242574
5  0.329502  0.053846  0.007722  ...  0.000000  0.000000  0.161172
6  0.590308  0.150442  0.035556  ...  0.000000  0.000000  0.301653
7  0.765306  0.709898  0.664384  ...  0.553633  0.520833  0.621711
8  0.759777  0.505618  0.395480  ...  0.195402  0.150289  0.484305
9  0.884444  0.526786  0.340807  ...  0.150000  0.118721  0.597458

[10 rows x 8 columns]

In [ ]:
# Create correlation matrix for just Features to determine different models to test
corr_matrix = features_df.corr().abs().round(2)

# display shows all of a dataframe
display(corr_matrix)

           c_1   c_2   c_3   c_4   c_5   c_6   c_7  lcs_word
c_1       1.00  0.94  0.90  0.89  0.88  0.87  0.87      0.97
c_2       0.94  1.00  0.99  0.98  0.97  0.96  0.95      0.98
c_3       0.90  0.99  1.00  1.00  0.99  0.98  0.98      0.97
c_4       0.89  0.98  1.00  1.00  1.00  0.99  0.99      0.95
c_5       0.88  0.97  0.99  1.00  1.00  1.00  1.00      0.95
c_6       0.87  0.96  0.98  0.99  1.00  1.00  1.00      0.94
c_7       0.87  0.95  0.98  0.99  1.00  1.00  1.00      0.93
lcs_word  0.97  0.98  0.97  0.95  0.95  0.94  0.93      1.00

In [ ]:
def train_test_data(complete_df, features_df, selected_features):
    '''Gets selected training and test features from given dataframes, and 
       returns tuples for training and test features and their corresponding class labels.
       :param complete_df: A dataframe with all of our processed text data, datatypes, and labels
       :param features_df: A dataframe of all computed, similarity features
       :param selected_features: An array of selected features that correspond to certain columns in `features_df`
       :return: training and test features and labels: (train_x, train_y), (test_x, test_y)'''
    
    selected_features_df = features_df[selected_features]
    
    # get the training features
    train_x = np.array(selected_features_df[complete_df['Datatype'] == 'train'])
    # And training class labels (0 or 1)
    train_y = np.array(complete_df[complete_df['Datatype'] == 'train']['Class'])
    
    # get the test features and labels
    test_x = np.array(selected_features_df[complete_df['Datatype'] == 'test'])
    test_y = np.array(complete_df[complete_df['Datatype'] == 'test']['Class'])
    
    return (train_x, train_y), (test_x, test_y)

In [ ]:
test_selection = list(features_df)[:2] # first couple columns as a test
# test that the correct train/test data is created
(train_x, train_y), (test_x, test_y) = train_test_data(complete_df, features_df, test_selection)

# params: generated train/test data
tests.test_data_split(train_x, train_y, test_x, test_y)

Tests Passed!

In [ ]:
display(corr_matrix)

           c_1   c_2   c_3   c_4   c_5   c_6   c_7  lcs_word
c_1       1.00  0.94  0.90  0.89  0.88  0.87  0.87      0.97
c_2       0.94  1.00  0.99  0.98  0.97  0.96  0.95      0.98
c_3       0.90  0.99  1.00  1.00  0.99  0.98  0.98      0.97
c_4       0.89  0.98  1.00  1.00  1.00  0.99  0.99      0.95
c_5       0.88  0.97  0.99  1.00  1.00  1.00  1.00      0.95
c_6       0.87  0.96  0.98  0.99  1.00  1.00  1.00      0.94
c_7       0.87  0.95  0.98  0.99  1.00  1.00  1.00      0.93
lcs_word  0.97  0.98  0.97  0.95  0.95  0.94  0.93      1.00

In [ ]:
selected_features = ['c_1', 'c_6', 'lcs_word']


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""

(train_x, train_y), (test_x, test_y) = train_test_data(complete_df, features_df, selected_features)

# check that division of samples seems correct
# these should add up to 95 (100 - 5 original files)
print('Training size: ', len(train_x))
print('Test size: ', len(test_x))
print()
print('Training df sample: \n', train_x[:10])

Training size:  70
Test size:  25

Training df sample:
 [[0.39814815 0.         0.19178082]
 [0.86936937 0.38248848 0.84649123]
 [0.59358289 0.06043956 0.31606218]
 [0.54450262 0.         0.24257426]
 [0.32950192 0.         0.16117216]
 [0.59030837 0.         0.30165289]
 [0.75977654 0.1954023  0.48430493]
 [0.51612903 0.         0.27083333]
 [0.44086022 0.         0.22395833]
 [0.97945205 0.74468085 0.9       ]]

In [ ]:
#pd.concat([pd.DataFrame(test_y), pd.DataFrame(test_x)], axis=1)

In [ ]:
def make_csv(x, y, filename, data_dir):
    '''Merges features and labels and converts them into one csv file with labels in the first column.
       :param x: Data features
       :param y: Data labels
       :param file_name: Name of csv file, ex. 'train.csv'
       :param data_dir: The directory where files will be saved
       '''
    # make data dir, if it does not exist
    if not os.path.exists(data_dir):
        os.makedirs(data_dir)
    
    
    # combine data and sent to csv
    pd.concat([pd.DataFrame(y), pd.DataFrame(x)], axis=1) \
        .to_csv(os.path.join(data_dir, filename), header=False, index=False)
    
    # nothing is returned, but a print statement indicates that the function has run
    print('Path created: '+str(data_dir)+'/'+str(filename))

In [ ]:
fake_x = [ [0.39814815, 0.0001, 0.19178082], 
           [0.86936937, 0.44954128, 0.84649123], 
           [0.44086022, 0., 0.22395833] ]

fake_y = [0, 1, 1]

make_csv(fake_x, fake_y, filename='to_delete.csv', data_dir='test_csv')

# read in and test dimensions
fake_df = pd.read_csv('test_csv/to_delete.csv', header=None)

# check shape
assert fake_df.shape==(3, 4), \
      'The file should have as many rows as data_points and as many columns as features+1 (for indices).'
# check that first column = labels
assert np.all(fake_df.iloc[:,0].values==fake_y), 'First column is not equal to the labels, fake_y.'
print('Tests passed!')

Path created: test_csv/to_delete.csv
Tests passed!

In [ ]:
! rm -rf test_csv

In [ ]:
data_dir = 'plagiarism_data'

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""

make_csv(train_x, train_y, filename='train.csv', data_dir=data_dir)
make_csv(test_x, test_y, filename='test.csv', data_dir=data_dir)

Path created: plagiarism_data/train.csv
Path created: plagiarism_data/test.csv

In [ ]:
pip install

In [ ]:
import pandas as pd
import boto3
import sagemaker

ModuleNotFoundError: ignored

In [ ]:
# Load train and test data
import os
import numpy as np

train = pd.read_csv(os.path.join(data_dir, 'train.csv'), header=None)

train_y = train.loc[:,0]
train_x = train.loc[:, 1:3]

In [ ]:
# Convert to RecordSet
train_x_np = np.array(train_x).astype('float32')
train_y_np = np.array(train_y).astype('float32')

formatted_train_data = estimator.record_set(train_x_np, labels=train_y_np)

In [ ]:
%%time

# Train your estimator on S3 training data
estimator.fit(formatted_train_data)

In [ ]:
%%time

# deploy your model to create a predictor
predictor = estimator.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge')

In [ ]:
import os

# read in test data, assuming it is stored locally
test_data = pd.read_csv(os.path.join(data_dir, "test.csv"), header=None, names=None)

# labels are in the first column
test_y = test_data.iloc[:,0]
test_x = test_data.iloc[:,1:]

In [ ]:
# First: generate predicted, class labels
test_x = np.array(test_x).astype('float32')
test_y = np.array(test_y)
test_y_preds = predictor.predict(test_x)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test that your model generates the correct number of labels
assert len(test_y_preds)==len(test_y), 'Unexpected number of predictions.'
print('Test passed!')

In [ ]:
test_y_preds = np.array([x.label['predicted_label'].float32_tensor.values[0] for x in test_y_preds])
test_y_preds

In [ ]:
# Second: calculate the test accuracy
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(test_y, test_y_preds)

print(accuracy)


## print out the array of predicted and true labels, if you want
print('\nPredicted class labels: ')
print(test_y_preds)
print('\nTrue class labels: ')
print(test_y)